name: Build and Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # If using static export (optional)
      # - name: Export Next.js app
      #   run: npm run export

      - name: Archive production build
        run: zip -r build-artifact.zip .next node_modules package.json package-lock.json next.config.js

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: build-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}       # Your App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # From Azure Portal
          package: build-artifact.zip
