name: Build and deploy Node.js app to Azure Web App - nextjs-app-us

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install all dependencies
        run: |
          echo "Installing dependencies..."
          npm ci

      - name: Build the Next.js app
        run: |
          echo "Building Next.js app..."
          npm run build

      - name: Install production dependencies only
        run: |
          npm ci --production

      - name: Create .env file for production
        run: |
          echo "NODE_ENV=production" > .env
          echo "PORT=8080" >> .env

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !.git
            !.github

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files for debugging
        run: ls -la

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_915382F70F4E4F28B70CDAB068C586EF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_673F08D0288D4453A20C692355AB0DFD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6F457702E8C94225BAEB48A27C23CCFF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nextjs-app-us'
          slot-name: 'Production'
          package: .