name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      # Ensure node_modules are included (Azure needs them at runtime)
      - name: Archive production build
        run: |
          mkdir -p deploy
          cp -r .next package.json server.js node_modules deploy/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nextjs-app-us
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .
