name: Deploy Next.js to Azure App Service

on:
  push:
    branches:
      - main 

jobs:
  build-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Ensure it's a fresh checkout every time
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: |
          export NEXT_PUBLIC_BUILD_TIMESTAMP=$(node -e 'console.log(Date.now())')
          echo "The build timestamp is: $NEXT_PUBLIC_BUILD_TIMESTAMP"
          npm run build

      # Ensure node_modules are included (Azure needs them at runtime)
      - name: Archive production build
        run: |
          mkdir -p deploy

          # Copy EVERYTHING except what's in .gitignore (smart approach)
          rsync -a --exclude-from=.gitignore . deploy/

          # Remove files/folders we never want in deployment
          rm -rf deploy/.git deploy/.github

          # The .next folder was excluded by .gitignore, so we need to add it back
          cp -r .next/ deploy/

          # Switch to the deploy directory and install only production dependencies
          cd deploy
          npm ci --only=production

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: next-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build-code

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: next-app
          path: ./deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nextjsapp-web
          resource-group: azurewebapp
          package: ./deploy
